services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    ports:
      - "8080:8000"    # ← changed external port to 8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RETENTION_HOURS=24
    volumes:
      - ./storage:/app/storage
    depends_on:
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RETENTION_HOURS=24
    volumes:
      - ./storage:/app/storage
    depends_on:
      redis:
        condition: service_healthy
    command: rq worker pipeline --url redis://redis:6379
